#!/usr/bin/env bash
# Install the HAProxy LB
sudo apt-get update
sudo apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo "
frontend localserv
	 bind *:80
	 mode http
	 default_backend webservs
backend webservs
	mode http
	balance roundrobin
	server 138029-web-01 54.144.157.180:80
	server 138029-web-02 35.153.83.92:80
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
